graph TD
    subgraph STARTSG [ ]
      START{{start}}
    end
    subgraph Login [ ]
      login_title["Login"]
      login_disconnect{{on <disconnect>}}
      login0([login0])
      login1([login1])
      login2([login2])
      login3([login3])
      login4([login4])
      login5([login5])
      login6([login6])
    end
    subgraph CommandLoop [ ]
      cmdlp_title["Command Loop"]
      cmdlp_disconnect{{on <disconnect>}}
      cmdlp0([cmdlp0])
      cmdlp1([cmdlp1])
      cmdlp2([cmdlp2])
      cmdlp3([cmdlp3])
      cmdlp4([cmdlp4])
      cmdlp5([cmdlp5])
      cmdlp6([cmdlp6])
    end
    subgraph Play [ ]
      play_title["Play"]
      play0([play0])
      play2([play1])
      play6([play2])
      play8([play3])
      subgraph Weapon [ ]
        weapon_title["Weapon"]
        play1([weapon0])
        play3([weapon1])
        play4([weapon2])
        play5([weapon3])
        play7([weapon4])
      end
    end
   subgraph ENDSG [ ]
      END{{end}}
      logout([logout])
    end

    START -->|"<connect><br>output(''Welcome to ROCK-PAPER-SCISSORS!'')"| login0


    login0 --> login1

    login1 ---->|"output(''Enter username:'')<br>input(uname)"| login2

    login2 -->|"?(!alphanumeric(uname))<br/>output(''Invalid username (`{{uname}}`)'')"| login1
    login2 -->|"?(alphanumeric(uname) && !db.has_key(uname))<br/>output(''Welcome new user!'')"| login3
    login2 -->|"?(alphanumeric(uname) && db.has_key(uname))"| login4

    login3 ---->|"output(''Enter initial password:'')<br>input(passwd)"| login5

    login5 -->|"?(passwd != '''' && db.create_user(uname,passwd))"| cmdlp0
    login5 -->|"?(passwd != '''' && !db.create_user(uname,passwd))<br>output(''User {{uname}} already online'')<br><terminate>"| END
    login5 -->|"?(passwd == '''')<br>output(''Invalid password'')"| login3

    login4 ---->|"output(''Enter pasword:'')<br>input(passwd)"| login6

    login6 -->|"?(passwd == db.password(uname) && db.login(uname))"| cmdlp0
    login6 -->|"?(passwd == db.password(uname) && !db.login(uname))<br>output(''User {{uname}} already online'')<br><terminate>"| END
    login6 -->|"?(passwd != db.password(uname))<br>output(''Incorrect password'')"| login4

    login_disconnect --> END


    cmdlp0 ---->|"output(''Enter command {passwd,play,players,stats,quit} [{{command_timeout}}s timeout]:'')<br>input(cmd)"| cmdlp1
    cmdlp1 -->|"?(!timeout({{command_timeout}}) && cmd == ''passwd'')"| cmdlp2
    cmdlp1 -->|"?(!timeout({{command_timeout}}) && cmd == ''play'')<br>output(''Waiting for opponent [{{play_timeout}} timeout]'')"| cmdlp3
    cmdlp1 -->|"?(!timeout({{command_timeout}}) && cmd == ''players''<br>output(''Online users: {{db.players()}}''))"| cmdlp0
    cmdlp1 -->|"?(!timeout({{command_timeout}}) && cmd == ''standings'')<br>output(''Standings: {{db.standings()}}'')"| cmdlp0
    cmdlp1 -->|"?(!timeout({{command_timeout}}) && cmd == ''stats'')<br>output(''{{uname}}: {{db.stats(uname)}}'')"| cmdlp0
    cmdlp1 ---->|"?(!timeout({{command_timeout}}) && cmd == ''quit'')<br>output(''Goodbye!'')<br><terminate>"| logout
    cmdlp1 ---->|"?(timeout({{command_timeout}}))<br>output(''Timeout after {{command_timeout}}s'')<br><terminate>"| logout
    cmdlp1 -->|"?(!timeout({{command_timeout}}) && ![''passwd'',''play'',''players'',''standings'',''stats'',''quit''].contains(cmd)<br>output(''Invalid command (`{{cmd}}`)'')"| cmdlp0

    cmdlp2 -->|"output(''Enter (old) password:'')<br>input(old_passwd)"| cmdlp4
    cmdlp4 -->|"?(old_passwd != db.password(uname))<br>output(''Incorrect password'')"| cmdlp2
    cmdlp4 -->|"?(old_passwd == db.password(uname))"| cmdlp5

    cmdlp5 -->|"output(''Enter (new) password:'')<br>input(new_passwd)"| cmdlp6
    cmdlp6 -->|"?(passwd == '''')<br>output(''Invalid password'')"| cmdlp5
    cmdlp6 -->|"?(passwd != '''')<br>db.set_passwd(uname,new_passwd)"| cmdlp0

    cmdlp3 ---->|"?(timeout({{play_timeout}}))<br>output(''Sorry, no opponents are ready to battle.'')"| cmdlp0
    cmdlp3 ---->|"?(!timeout({{play_timeout}}) && opponent = play.request(uname))"| play0

    cmdlp_disconnect --> logout


    play0 -->|"output(''{uname} versus {opponent}!!'')"| play1
    play0 -->|"<disconnect>"| play2

    play1 -->|"wstime = now()"| play3

    play2 -->|"(oweapon,outcome) = play.finish(None)<br>db.inc_stats_by_outcome(uname,outcome)"| logout

    play3 -->|"wtimeout = wstime + {{weapon_timeout}} - now()"| play4

    play4 ---->|"output(''Choose your weapon {r,p,s} [{{wtimeout}}s timeout]:'')<br>input(wstr)"| play5
    play4 -->|"<disconnect>"| play2

    play5 ---->|"?(timeout(wtimeout))<br>weapon = None"| play6
    play5 -->|"?(!timeout(wtimeout) && wstr == ''r'')<br>weapon = Some(Rock)"| play6
    play5 -->|"?(!timeout(wtimeout) && wstr == ''p'')<br>weapon = Some(Paper)"| play6
    play5 -->|"?(!timeout(wtimeout) && wstr == ''s'')<br>weapon = Some(Scissors)"| play6
    play5 ---->|"?(!timeout(wtimeout) && ![''r'',''p'',''s''].contains(wstr))"| play7

    play6 -->|"(oweapon,outcome) = play.finish(weapon)<br>db.inc_stats_by_outcome(uname,outcome)"| play8

    play7 -->|"output(''Invalid weapon (`{{wstr}}`)'')"| play3
    play7 -->|"<disconnect>"| play2

    play8 ---->|"output(''{{opponent}}} plays {{oweapon}}; you {{outcome}}!'')"| cmdlp0
    play8 ---->|"<disconnect>"| logout


    logout -->|"db.loutout(uname)"| END
