# Programming Assignment 01

In this initial programming assignment, you will implement two simple utilities:
`rwc` (Rust Word Count, to report the number of newlines, words, and characters
in a source file) and `rlf` (Rust Letter Frequency, to report the frequency of
letters in a source file).  The goal is to become comfortable with Rust
development (e.g., using `cargo`) and to practice some simple iterative
algorithms.

## Sources and Submission

:duetime: 11:59pm
:dueday: Friday, January 21, 2022

We have setup a Git repository for each student on `git.cs.rit.edu`.  To _clone_
your repository, run either the command:

  git clone https://git.cs.rit.edu/psr2215/<ritid>psr.git

or, if you have setup SSH keys on `git.cs.rit.edu`, the command:

  git clone gitlab@git.cs.rit.edu:psr2215/<ritid>psr.git

If prompted for a password, then use your `__ritid__@cs.rit.edu` password.

Upon a successful clone, a directory called `__ritid__psr` will be created in
the current directory.  Over the course of the semester, programming assignments
will be stored as sub-directories within the `__ritid__psr` directory.

Next, _configure_ your local clone to _merge_ (and to not _rebase_) changes from
the _origin_ (a.k.a., upstream) repository on `git.cs.rit.edu`:

  git config pull.rebase false

Sources for Programming Assignment&nbsp;01 have been (or will shortly be)
committed to your repository in the `prog01` sub-directory.  If you cloned your
repository before the Programming Assignment&nbsp;01 sources have been
committed, then you will need to _pull_ the upstream changes into your local
clone, by running the command:

  git pull origin

from the `__ritid__psr` directory.  It is best to _pull_ with no uncommitted
changes in your local clone, but most commits made to the upstream repository
will only add a new top-level directory and there should be no merge conflicts.

We will tag homeworks in the Git repositories at {duetime} on {dueday}; make
sure that you have _committed_ and _pushed_ your final version before that time.
To do so, run the commands:

  git commit -a
  git push origin main

from the `__ritid__psr` directory.  If old programming assignment comments or
new programming assignment sources have been committed to your repository since
you last pulled, then you will receive an error message when trying to push:

  error: failed to push some refs to 'git.cs.rit.edu:psr2215/<ritid>psr.git'
  hint: Updates were rejected because the remote contains work that you do
  hint: not have locally. This is usually caused by another repository pushing
  hint: to the same ref. You may want to first integrate the remote changes
  hint: (e.g., 'git pull ...') before pushing again.
  hint: See the 'Note about fast-forwards' in 'git push --help' for details.

To proceed, you will need to _pull_ the upstream changes into your local clone
and then _push_ your local changes upstream, by running the commands:

  git pull origin
  git push origin main

from the `__ritid__psr` directory.


## `rwc` (Rust Word Count)

The `rwc` utility reports the number of newlines, word, and (Unicode) characters
in a (UTF-8 encoded) source file.  (Technically, the standard Unix `wc` utility
reports the number of bytes, rather than (Unicode) characters, in an arbitrary
sources file.  The subtle distinction won't make any difference for "normal"
ASCII text files.)

Complete the `+newlines_words_chars+` function:

[source,rust]
----
fn newlines_words_chars(src: &str) -> (u64, u64, u64)
----

The `+newlines_words_chars+` function returns a three tuple of`u64` values; the
first component should contain the count of newlines in the input slice; second
component should contain the count of words in the input slice; the third
component should contain the count of chracters in the input slice.  Note that a
word is any contiguous sequence of non-whitespace characters.

### Discussion/Hints

The `&str` is a _string slice_, which is described in
https://doc.rust-lang.org/book/ch04-03-slices.html[The Rust Programming
Language: 4. Understanding Ownership].  However, for the purposes of this
assignment, it suffices to think of `&str` as an array of Unicode characters.
You can iterate through the characters in the string slice using:

[source,rust]
----
for c in src.chars() { ... }
----

There are many useful https://doc.rust-lang.org/std/primitive.char.html[methods
of the primitive type `char`].  For this program, the most useful is
`is_ascii_whitespace`.

### Examples

----
$ cargo -q test

running 9 tests
.........
test result: ok. 9 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.04s

$ cat assets/fruits.txt
1. apple!
2. banana?
3. cherry$
4. date#
$ cargo -q run assets/fruits.txt
4 8 41 assets/fruits.txt
$ cargo -q run assets/gettysburg.txt
36 279 1505 assets/gettysburg.txt
$ cargo -q run assets/sherlock_holmes.txt 
12759 109463 608162 assets/sherlock_holmes.txt
----

## `rlf` (Rust Letter Frequency)

The `rlf` utility reports the frequency of ASCII letters in a source file.

Complete the `+letter_count+`, `+count_to_frequency+`, and `+letter_frequency+` functions:

[source,rust]
----
fn letter_count(src: &str) -> [u64; 26]
fn count_to_frequency(inp: [u64; 26]) -> [f64; 26]
fn letter_frequency(src: &str) -> [f64; 26]
----

The `+letter_count+` function returns an array of 26 `u64` values; the first
entry of the array should contain the count of `'a'` and `'A'` characters in the
input slice; the 26th entry of the array should contain the count of `'z'` and
`'Z'` characters in the input slice.

The `+count_to_frequency+` function takes an array of 26 `u64` values and
returns an array of 26 `f64` values; the first entry of the output array should
contain the frequency (percentage, as a value between 0 and 1) of the value of
the first entry of the input array relative to the values of all entries of the
input array; the 26th entry of the output array should contain the frequency
(percentage) of the value of the 26th entry of the input array relative to the
values of all entries of the input array.

The `+letter_frequency+` function returns an array of 26 `f64` values; the first
entry of the array should contain the frequency (percentage, as a value between
0 and 1) of `'a'` and `'A'` characters in the input slice; the 26th entry of the
array should contain the count of `'z'` and `'Z'` characters in the input slice.

Also, complete the `+main+` function.  The provided code in `+main+` reads the
source file contents into `src: String`.  The `+main+` function should then go
on to compute and report the (non-zero) frequencies of the ASCII letters in the
source file.  The report should be a table like the following:

----
B:  8.333%
D: 16.667%
E:  8.333%
G:  8.333%
L:  8.333%
O: 25.000%
R:  8.333%
W:  8.333%
Y:  8.333%
----

Note that frequencies are reported as percentages, shown with a precision of
three digits after the decimal point, and aligned at the decimal point.

## Discussion/Hints

For this program, the useful methods of the primitive type `char` might include
`+is_ascii_alphabetic+`, `+is_ascii_lowercase+`, `+is_ascii_uppercase+`,
`+make_ascii_lowercase+`, `+make_ascii_uppercase+`, `+to_ascii_lowercase+`,
`+to_ascii_uppercase+`.

You can cast values of one primitive type to another using the syntax
`_expr_ as _type_`.  For example:

[source,rust]
----
let c: char = 'A';
let c_as_u32: u32 = c as u32;
let c_as_usize: usize = c as usize;

let i: usize = 12345;
let i_as_u16 = i as u16;

let n: u8 = 65;
let n_as_char: char = n as char;
----

Note that only values of type `u8` can be (directly) cast to `char`; however,
larger integer types can be first cast to `u8` and then cast to `char`.

Note that array indices must be of type `usize`.

You can certainly implement numeric loops using a mutable variable and `while`:

[source,rust]
----
let mut i = 0;
while i < 100 {
    ...
    i += 1;
};
----

However, it is more idiomatic to iterate with a
https://doc.rust-lang.org/std/ops/struct.Range.html[range object] introduced by
a https://doc.rust-lang.org/reference/expressions/range-expr.html[range
expression]:

[source,rust]
----
for i in 0..100 {
    ...
};
----

Recall that you can iterate through the elements of an array with `+for+`:

[source,rust]
----
let array: [i32; 4] = [1,2,3,4];
for x in array {
    ...
};
----

Finally, the https://doc.rust-lang.org/std/fmt/[`std::fmt` documentation]
describes the formatting arguments that can be used to control the width,
fill/alignment, and precision of arguments formatted with the `format!` and
`println!` macros.

### Examples

----
$ cargo -q test

running 18 tests
..................
test result: ok. 18 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.04s

$ cat assets/fruits.txt
1. apple!
2. banana?
3. cherry$
4. date#
$ cargo -q run assets/fruits.txt
A: 23.810%
B:  4.762%
C:  4.762%
D:  4.762%
E: 14.286%
H:  4.762%
L:  4.762%
N:  9.524%
P:  9.524%
R:  9.524%
T:  4.762%
Y:  4.762%
$ cargo -q run assets/gettysburg.txt
A:  8.983%
B:  1.356%
C:  2.712%
D:  5.085%
E: 14.153%
F:  2.288%
G:  2.542%
H:  6.864%
I:  5.847%
K:  0.254%
L:  3.729%
M:  1.186%
N:  6.695%
O:  7.966%
P:  1.271%
Q:  0.085%
R:  6.949%
S:  3.983%
T: 10.847%
U:  1.864%
V:  2.034%
W:  2.373%
Y:  0.932%
$ cargo -q run assets/sherlock_holmes.txt 
A:  8.109%
B:  1.487%
C:  2.500%
D:  4.254%
E: 12.277%
F:  2.093%
G:  1.859%
H:  6.595%
I:  7.004%
J:  0.122%
K:  0.823%
L:  3.972%
M:  2.709%
N:  6.644%
O:  7.788%
P:  1.642%
Q:  0.097%
R:  5.761%
S:  6.250%
T:  9.073%
U:  3.000%
V:  1.025%
W:  2.568%
X:  0.130%
Y:  2.177%
Z:  0.041%
----
